### ISSUE TITLE
Many animate.css animations bugged on IE 11

### ISSUE THREAD

**Issue by josephdietrich** [KevinBatdorf/liquidslider#132]
Testbox: IE 11.0.96.17107 on Windows 8.1

Animations work, but are bugged. On the example page at (http://kevinbatdorf.github.io/liquidslider/examples/page2.html), animations such as bouncing, flipping, and rotating don't seem to clip correctly to the liquid-slider container (for example, text flies out of the bounding box on rotateOut, and on many animations the next panel in the queue appears to the right of the container box).

**Comment by jagu51** [comment]
I have this problem on IE 11, too. Is there any solution?

**Comment by kosmo009** [comment]
I have this problem too on IE 11 and i cant´t find the solution. Have you an idea now?
