### ISSUE TITLE
Liquidslider crashes firefox 34

### ISSUE THREAD

**Issue by gistart** [KevinBatdorf/liquidslider#150]
Hi, i'm using liquidslider 2.3.8 and jq.easing 1.3.

I have 2 sliders on a page, and users occasionally report lags, hangs and other unpleasant issues with that page, even "script crashed" messages.

I figured out how to reproduce this: open my page in one tab and something else in other and start to switch between them. On like 10th or 15th switch firefox hangs, and "script crashed" message appears.

Sometimes firefox even crashes, sometimes it hangs with ~100% CPU and RAM usage.

Init code of slider:
```javascript
               $('#slider').liquidSlider({
                        continuous: true,
                        dynamicTabsPosition: "bottom",
                        slideEaseDuration: 700,
                        heightEaseDuration: 300,
                        hoverArrows: false,
                        mobileNavigation: false,
                        autoSlide: true,
                });
```

Disabling autoslide feature fixes the issue.

Screenshot of the issue: http://itmages.com/image/view/2140705/b7220d7f

**Comment by wro77** [comment]
Same problem here on Firefox 49.0.1, even with the standard slider I just downloaded on your website. I only set the autoslide to true and the script crashes after a while.

Any suggestions?
