### ISSUE TITLE
adding an accordion to liquid slider

### ISSUE THREAD

**Issue by codywright4** [KevinBatdorf/liquidslider#152]
I saw that you posted a tutorial on an earlier comment, to add an accordion to the liquid slider, I think you took the tutorial down, the link was dead. I tried implenting a dynamic accordion plug in into the the slider, but I am not very JavaScript savvy and was unsuccessful. I was trying to get height of the slider to adjust when I clicked on one of the tabs of the accordion. If you have time to repost the tutorial, it would be greatly appreciated. Thank you. Great btw, the slider is probably the best I've seen.

**Comment by KevinBatdorf** [comment]
Basically, you need to use the accordian's hook to adjust the slider height. Find an accordian plugin that has a pre-transition function (or write your own) where you can run code before it opens/closes, then use the following code:

```javascript
var api = $.data( $('#slider-id')[0], 'liquidSlider');
api.adjustHeight(true, _this.getHeight());
```
