### ISSUE TITLE
issue on Windows Google Chrome

### ISSUE THREAD

**Issue by iontorres** [KevinBatdorf/liquidslider#157]
Hi, Liquid slider works perfect in all resolutions of chrome in Mac, but at the time I try it on Windows Chorme it gives me a little issue adding a margin on the left of each image.

Mac screen 1280 x 800

![captura de pantalla 2015-05-05 a las 17 16 21](https://cloud.githubusercontent.com/assets/2818870/7484095/a13b3b3c-f34a-11e4-8b7f-57520e52e9ae.png)

Windows Screen 1280 x 800
![marvi windows](https://cloud.githubusercontent.com/assets/2818870/7484202/a7813a4a-f34b-11e4-87b1-6b6c612bf84b.png)

The curious thing here is when I resize the window the slider fits without problem.

**Comment by KevinBatdorf** [comment]
How do the examples work? Are there any hints int he developer tools?

You can try adding this to the settings

```javascript
onload: function() { this.adjustHeight() }
```

if `adjustHeight` doesn't work, try `transition`

**Comment by iontorres** [comment]
Oh sorry I miss the example, it can be seen on this link: 
http://www.marvi.com.mx/09/

**Comment by KevinBatdorf** [comment]
Did you fix it? I don't see an error. The error you posted could mean a few different things.
