### ISSUE TITLE
continuous:false is not working simply

### ISSUE THREAD

**Issue by sushilpal** [KevinBatdorf/liquidslider#159]
i am using the following code 

    $('#main-slider').liquidSlider(
	{
	 continuous:false
  	});

in index.html

provided in master.zip

slider is scrolling continuously.

**Comment by KevinBatdorf** [comment]
Seems to be working fine for me. Want to show me an example? Are you sure you dont mean autoslide?

**Comment by sushilpal** [comment]
Thanks for quick response KevinBatdorf.
working fine ,it am doing mistake.
one more question
how to stop cyclic scrolling.my requirement is ,scrolling start from 1 and go till 4 and back from 4 to 1 but not jump from 1 to 4.only forward and backward not cyclic .
