### ISSUE TITLE
slider not working with apache web server

### ISSUE THREAD

**Issue by aditi89** [KevinBatdorf/liquidslider#164]
I am using codaSlider3.0.
My problem is when  I Am making sample web page coda-slider is working properly.But when I am running that same page in Apache web server coda-slider is not working and all the content is coming in plain html format..

What can be the issue??

**Comment by KevinBatdorf** [comment]
Could be anything, but most likely not Coda Slider related...

Do you know how to check the developer console in your browser? Look there first for errors.

**Comment by aditi89** [comment]
I checked it through developer console and it came out to be some permission error.
Now working.Thanks.
