### ISSUE TITLE
hashCrossLinks causes an appending anchor on the url

### ISSUE THREAD

**Issue by CMCDragonkai** [KevinBatdorf/liquidslider#5]
Hello,

I'm currently using hashCrossLinks to allow external hash names to push and pull the slider. Everything is working well. However, on page load, the hash name of the first slide is appended on the url.

So if I go to http://www.example.com/
It will immediately change to http://www.example.com/#first_slider_name

Is there anyway to hide the hash name on page load, as it doesn't seem to do anything? Also could you update the documentation to reflect hashCrossLink?

Here is the options I'm currently using:

``` javascript
/* Liquid Slider (http://liquidslider.kevinbatdorf.com/) */
    $('#mid_slider_template').liquidSlider({
        dynamicTabs: false, //remove the tabs from the slider
        panelTitleSelector: "h3.slide_title", //use the h3 class=slide_title as the title of the slide
        topScrolling:true, //automatically scroll to the slide when triggered by a relevant anchor
        topScrollingExtraPixels: 25, //add 25 pixels to the top when scrolled to the relevant slide panel
        keyboardNavigation: true, //allow left and right keys to scroll the slider
        crossLinks: true, //allow external anchors (not inside the slider) to push or pull to the relevant slide (anchors tags require: data-liquidslider-ref="SLIDER-ID")
        hashLinking: true, //allows for us to use hashes (#) as a link to push or pull slides
        hashCrossLinks: true, //allows us to use cross link's hashes as links to go to specific slides
        hashNames: true, //allows us to use names rather than numbers for the hashes
        hashTitleSelector: "h3.slide_title", //specifies the name of the hash which corresponds to the specific slide
    });
```

**Comment by amadika** [comment]
I'm looking for a fix to this same issue. I want the initial page load to not append the hashtag, because I'm using a scroll to hashtags on the page, and it automatically sends them to that area on page load instead of at the top. The old resolution links no longer work.

**Comment by KevinBatdorf** [comment]
I do it on [this page here](http://kevinbatdorf.github.io/liquidslider/examples/page1.html#advanced-controls) with the following code:
```javascript
<a href="#" class="enable-hash">Enable Hash Linking</a>

$('#slider-4').liquidSlider({
    //hashLinking:true,
  });
  var api2 = $.data( $('#slider-4')[0], 'liquidSlider');
  $('.enable-hash').on('click', function(e){
    e.preventDefault();
    api2.options.hashLinking = true;
    api2.buildHashTags();
  });
```
That works for clicking on a button. You could probably put that code in the final callback and get your desired result. 
```javascript
callback: function() {
  this.options.hashLinking = true;
  this.buildHashTags();
}
```

**Comment by amadika** [comment]
How would that look to add to the callback? I've not used them before.

**Comment by KevinBatdorf** [comment]
Click the link I shared above and check the next section. It explains it there.

**Comment by amadika** [comment]
So, I put it here:
<code>$('#main-slider').liquidSlider({
			continuous:false,
			crossLinks:true,
			dynamicTabs: true,
			hashLinking: true,
			dynamicArrows: false,
			slideEaseFunction:'animate.css',
			slideEaseDuration:500,
			heightEaseDuration:500,
			animateIn:"fadeInDown",
			animateOut:"fadeOutDown",
			callback: function() {
			  this.options.hashLinking = true;
			  this.buildHashTags();
			}
		  });
		  var api2 = $.data( $('#main-slider')[0], 'liquidSlider');</code>
But that doesn't appear to be working. Any suggestions?

**Comment by amadika** [comment]
Ah, realized I left hashlinking set to true. That fixes it! Thanks so much!

**Comment by amadika** [comment]
Ah, but that doesn't allow me to link to that specific section from another page directly if I want to.

**Comment by KevinBatdorf** [comment]
I think what you want is to disable your script that does the scrolling, at least in the beginning. Maybe you could initialize that script within the Liquid Slider callback function?
