### ISSUE TITLE
Blurred Text Field

### ISSUE THREAD

**Issue by ghost** [KevinBatdorf/liquidslider#67]
Hello, i have just downloaded and tested your Slider, which is almost perfect.
But using it with an iPhone 3gs i get a blurred Text Field.
The Text who´s inside the <div></div> Tags.
To be sure, i just opened the Examples on your Page and do get the same Result as on my Test Site

Edit: Text is ok on normal Width, but if i enlarge the Website/Screen it stays blurred

**Comment by AmandaUCSC** [comment]
@KevinBatdorf  I'm having the same issue and there has been no modification of the widths. I presume you mean these settings? :

```
.liquid-slider .ls-panel {  
  width: 970px;
  display: block;
  float: left;
}

.liquid-slider {
  background: #FFFFFF;
  width: 970px;
  margin: 0 auto;
  float: left;
  overflow: hidden;
  position: relative;
}
```

**Comment by KevinBatdorf** [comment]
Hi @AmandaUCSC 

Can you explain a little more? This issue is 4 years old and I doubt you're using an iPhone 3gs ;-)

**Comment by AmandaUCSC** [comment]
True. FWIW it seems to be Windows 10 Chrome. I don't see the same issue using Microsoft Edge (but who uses that?!).

**Comment by KevinBatdorf** [comment]
I'm traveling right now and can't test on Windows for another two weeks, but how about the demo site? Does that look broken too?

http://kevinbatdorf.github.io/liquidslider/

You have a screenshot or is the site online somewhere?

**Comment by AmandaUCSC** [comment]
Sure - site isn't online, so here is the comparison using the demo site. Left is Firefox, right is Chrome.   

![liquid slider blurry](https://user-images.githubusercontent.com/2671514/32491753-21a277fa-c3b8-11e7-8323-a5b94ac71da6.JPG)

**Comment by KevinBatdorf** [comment]
What's the issue with these? The styling is slightly different because of browser defaults.

**Comment by AmandaUCSC** [comment]
So here's a screenshot from our site. We use the slider to slide between English and Chinese translations... the Chinese in Chrome is on the left, Firefox on the right. I can't explain why one is blurry and the other not. I thought it might be the settings mentioned above (panel or slider width) but when I remove those it just made things even fuzzier and almost blurry.

![chrome and firefox](https://user-images.githubusercontent.com/2671514/32492684-781f8458-c3bb-11e7-8b54-09c0a8585f78.JPG)

**Comment by AmandaUCSC** [comment]
To contrast, this is what the text looks like for a document NOT using the slider. Notice there is no fuzzy look at all. So it's not just a browser rendering issue.

![chrome firefox 2](https://user-images.githubusercontent.com/2671514/32492790-c919524e-c3bb-11e7-8825-d718737c4262.JPG)

**Comment by AmandaUCSC** [comment]
(As a side note, we really like the slider as an option for the translations, so we want to keep it! It is much better than other options used on newspaper websites like NYT! :) )

**Comment by KevinBatdorf** [comment]
It's how chrome renders text inside objects that can animate. It's a bug that has existed since forever. Actually, I think there is one attempt at a fix in the code already.

You can try this though:

```css
body {
	-webkit-font-smoothing: antialiased;
	-moz-osx-font-smoothing: antialiased;
	font-smoothing: antialiased;
}
```

[read more](https://wp-mix.com/font-smoothing-chrome-firefox/) here. There might be some other stuff you have to add as well.
